spring:
  application:
    name: "motorola"
  ai:
    openai:
      api-key: <secret>


management:
  datadog:
    metrics:
      export:
        enabled: false

storage:
  file:
    base-location: "upload"
    request-timeout: 15